#ifndef ROBOT_ERROR_H
#define ROBOT_ERROR_H

enum {
  ROBOT_ERROR_NONE,
  ROBOT_ERROR_BAD_ROBOT_ID,
  ROBOT_ERROR_ALLOC_FAILED,
  ROBOT_ERROR_OBJ_OUT_OF_BOUNDS,
  ROBOT_ERROR_OUT_OF_BOUNDS,
  ROBOT_ERROR_HEARTBEAT,
  ROBOT_ERROR_BAD_PASSWORD,
  ROBOT_ERROR_ID,
  ROBOT_ERROR_INVALID_MODEL,
  ROBOT_ERROR_LAST
};

#define THOR_PROTOCOL_VERSION 4

extern int16_t client_prot_ver;

#endif
