#ifndef THY_ERROR_H
#define THY_ERROR_H

enum {
  THYMIO_ERROR_NONE,
  THYMIO_ERROR_BAD_THYMIO_ID,
  THYMIO_ERROR_ALLOC_FAILED,
  THYMIO_ERROR_OBJ_OUT_OF_BOUNDS,
  THYMIO_ERROR_OUT_OF_BOUNDS,
  THYMIO_ERROR_HEARTBEAT,
  THYMIO_ERROR_BAD_PASSWORD,
  THYMIO_ERROR_ID,
  THYMIO_ERROR_LAST
};

enum {
  MODEL_THYMIO_II,
};

#define THYSIM_PROTOCOL_VERSION 4

extern sint16 client_prot_ver;

#endif
